log:
  exp_name: napoleon_-10_v3
guide:
  text: "A photo of Napoleon Bonaparte"
  shape_path: shapes/napoleon.obj
  guidance_scale: 10
  use_zero123plus: True
optim:
  seed: 100
  learn_max_z_normals: True
  alpha: -10
