log:
  exp_name: spiderman_5_1
guide:
  text: "A photo of Spiderman, {} view"
  append_direction: True
  shape_path: shapes/human.obj
  guidance_scale: 10
  second_model_type: "control_zero123"

  individual_control_of_conditions: True
  guidance_scale_i: 5
  guidance_scale_t: 1